slam_toolbox:
  ros__parameters:
    # Frames
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan

    # Modo
    mode: mapping
    use_sim_time: false

    # Mapa
    resolution: 0.05
    max_laser_range: 12.0

    # Actualización mínima para procesar scan
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5

    # Publicación
    map_update_interval: 2.0
    transform_publish_period: 0.02

    # Loop closing
    do_loop_closing: true
    loop_search_maximum_distance: 3.0

    # Solver
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_loss_function: None

    debug_logging: false
    throttle_scans: 1
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    use_map_saver: true
